<?php

namespace App\Helpers;

use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;
use Throwable;

class CacheHelper
{
    /**
     * Prefix used by every cache key generated by financial listings.
     * Keys are namespaced with this so we can invalidate by namespace
     * without depending on cache-tag support (which the `database`
     * driver does NOT provide).
     */
    public const FINANCE_LISTING_NAMESPACE = 'fin_listing_v1';

    /**
     * Determine whether the configured cache store supports cache tags.
     */
    public static function supportsTags(?object $store = null): bool
    {
        $store ??= Cache::getStore();

        return method_exists($store, 'tags');
    }

    /**
     * Flush cache tags when the configured store supports them.
     *
     * Database and file stores do not support tags. For those stores,
     * the fallback path is to drop the `fin_listing_v1:*` namespace
     * directly through Cache::delete()/Cache::flush() depending on what
     * is supported.
     *
     * NOTE: This avoids `Cache::flush()` which deletes every entry
     * system-wide; that can race with concurrent transactions.
     */
    public static function flushTags(array $tags): void
    {
        try {
            if (self::supportsTags()) {
                Cache::tags($tags)->flush();
                return;
            }

            // No-tag fallback: drop the financial listing namespace prefix
            // entries only. We do this conservatively by deleting any key
            // we can discover in the listing namespace.
            self::flushNamespace();
        } catch (Throwable $e) {
            // Cache invalidation is best-effort. Never turn a successful
            // financial write into a failed request because the cache is down.
            Log::warning('Cache tag invalidation failed', [
                'tags' => $tags,
                'error' => $e->getMessage(),
            ]);
        }
    }

    /**
     * Drop every cache key under the financial listing namespace.
     *
     * The `database` driver stores entries in `cache` table; we delete by
     * matching `key LIKE 'fin_listing_v1:%'`. This avoids touching any
     * other cached data (sessions, rate-limiters, etc.).
     */
    public static function flushNamespace(): void
    {
        try {
            $store = Cache::getStore();
            $prefix = config('cache.prefix', '') . self::FINANCE_LISTING_NAMESPACE;

            // Database store
            if (method_exists($store, 'connection')) {
                $connection = $store->connection();
                if (method_exists($connection, 'table')) {
                    $connection->table($store->getTable())
                        ->where('key', 'like', $prefix . '%')
                        ->delete();
                    return;
                }
            }

            // File store: scan the cache path and delete matching files
            if (property_exists($store, 'files')) {
                foreach ($store->files as $file) {
                    if (str_contains((string) $file, self::FINANCE_LISTING_NAMESPACE)) {
                        @unlink($file);
                    }
                }
            }
        } catch (Throwable $e) {
            Log::warning('Cache namespace flush failed', [
                'namespace' => self::FINANCE_LISTING_NAMESPACE,
                'error' => $e->getMessage(),
            ]);
        }
    }

    /**
     * Get a cache store that supports tagging if available, or fall back to
     * a namespaced key on the default store.
     *
     * @param array $tags  Used directly when the store supports tagging,
     *                     otherwise each tag is appended as a prefix to the
     *                     cache key so invalidation can be done by prefix.
     */
    public static function tags(array $tags)
    {
        if (self::supportsTags()) {
            return Cache::tags($tags);
        }

        $namespace = self::FINANCE_LISTING_NAMESPACE;

        // Build a tagged-key closure proxy.
        return new class($tags, $namespace)
        {
            public function __construct(private array $tags, private string $namespace) {}

            public function remember(string $key, $ttl, \Closure $callback)
            {
                $namespacedKey = $this->namespace . ':' . implode(',', $this->tags) . ':' . $key;

                return Cache::remember($namespacedKey, $ttl, $callback);
            }

            public function flush(): void
            {
                CacheHelper::flushNamespace();
            }
        };
    }
}
